### ISSUE TITLE
Collect data in files

### ISSUE THREAD

**Issue by oliviariccomi** [BITalinoWorld/revolution-android-api#11]
Hi! I'm doing my thesis on BITalino biosignals acquisition.
What I'm trying to do is collecting the data through the sensor and create different files depending on the signal.
My professor suggested me to use OpenCSV.
Since I'm not a pro in Android Studio, how should I edit the code to write the data in the file??
THANKS A LOT

**Comment by GRamosPlux** [comment]
Dear @oliviariccomi,

Thank you very much for opening this important improvement topic.
Understanding that a new student is start using **BITalino** in an important stage of his academic journey is always a great honour to our team!

Concerning the **OpenCSV** library, we are a little bit concerned that some issues can be raised in **Android**, considering past reports [(user discussion link)](https://sourceforge.net/p/opencsv/wiki/FAQ/#getting-noclassdeffounderror-when-using-android).

However, due to the relevance of this feature, the most recent commit [(commit link)](https://github.com/BITalinoWorld/revolution-android-api/commit/e1e9aedd7c27d9fd1d61cb5a310d9de655ea43dc) includes a proposal with the changes that should be applied to the code in order to achieve the CSV data storage goal.

I truly hope that the previous information can be helpful, however, if you consider that it don't fully meet your needs, please, do not hesitate to alert us!

**My best and sincere regards,**
@GRamosPlux

**Comment by oliviariccomi** [comment]
Thank you very much for your quick response. 
I've been trying the new code and it does create the csv file (I changed the file format), but the stream of data are not written in it. 
Do I have to edit anything else??

**Comment by GRamosPlux** [comment]
Dear **@oliviariccomi**,

Answering this challenge was a great pleasure to our team!
Thank you very much for providing this important feedback.

The reported behaviour is very peculiar, our team tried to replicate it and eventually we found a possible origin to explain this event.
Generally the created file needs to be programmatically closed to conclude the file writing procedure with success.

This programmatic "close" was done once the device enters in the **CONNECTED** state ([code link](https://github.com/BITalinoWorld/revolution-android-api/blob/e1e9aedd7c27d9fd1d61cb5a310d9de655ea43dc/sample-app/src/main/java/info/plux/pluxapi/sampleapp/DeviceActivity.java#L227-L233)), i.e., when the _Stop_ button is pressed.

Before exploring more complex possibilities, I would like to ask if you stopped the acquisition prior to opening the generated file?

I will carefully wait for your extremely valuable feedback!

**My best and sincere regards,**
@GRamosPlux

**Comment by oliviariccomi** [comment]
Thank you very much for the feedback! 
Yes! Before opening the generated file I stop the acquisition and disconnect the board but no stream is reported.

In the version of the code me and my professor made, we created a method createCsvFile() where there are both the writing and the closing of the file in a unique method. In that case it works but not through any library, I manually built a CSV file.
Then I called the method in the stop_button case (in the "onClick" method).
And that works, it generates the file with the stream of data.

Thank you very much for the help!!

**Comment by GRamosPlux** [comment]
Dear @oliviariccomi,

These are excellent news!
I am very glad for understanding that you found a functional solution, thank you very much for sharing this logic and for clarifying our past question.

Before officially closing the current issue, the **PLUX** team would like to understand if we can help in any further question related with this topic?

**My best and sincere regards,**
@GRamosPlux

**Comment by oliviariccomi** [comment]
Yes but is not a very efficient code so I wanted to try your code to generate an official CSV file. 
It still doesn't work when I stop and disconnect the board (I mean is still an empty file)
Thank a lot!!

**Comment by GRamosPlux** [comment]
Dear @oliviariccomi,

Thank you very much for this important clarification.
I will do my best to provide further support!

In order to deeply evaluate your experimental conditions, hoping that you don't consider inappropriate, I would like to request some additional information:

- Are you using the **Sample APP** (available in the repository) without changes (except the file extension adaptation) or this issue is being raised in your custom application?
- Which is the **Android** version under use?
- Will it be possible to share a small video demonstrating the steps that you are following since the APP launch until the evaluation of the file content?

Our team will carefully wait for your attentive feedback!

**Comment by oliviariccomi** [comment]
Hi!! Answering to your questions:
1) Yes, I'm using the SAMPLE APP without changes except for the extension change;
2) The version is Android Studio 4.1.1
Yes I can record a short video of the test. Should I upload it here?
Thanks a lot!! Olivia

**Comment by GRamosPlux** [comment]
Dear @oliviariccomi,

Thank you very much for your availability! 

Concerning the video, if you feel comfortable in sharing it with our community of users, you can post a **Google Drive** public link in this discussion.
Otherwise, if you prefer to do a single share, it will be a pleasure to provide my working e-mail: **gramos@plux.info**

Regarding the question 2, an extra doubt arose, are you using **Android 10** in the mobile device being tested?

**My best and sincere regards,**
@GRamosPlux

**Comment by GRamosPlux** [comment]
Dear  @oliviariccomi,

Thank you very much for sharing an extremely illustrative video, it was really helpful to find a very probable cause for the reported problem!

Essentially, due to my mistake, the original implementation only supported the file writing functionality in **BLE** devices.
A new commit was done (a few minutes ago) to include the support for classic **BTH** devices or **DUAL**, like yours.

Note, however, that this new commit was done in a recently created branch, so, you probably need to **fetch** your local version of the project and checkout into the new branch.

Our team truly hopes that this fix can be helpful to answer your needs, however, if the problem persists, please, do not hesitate proceed this discussion!

**My best and sincere regards,**
@GRamosPlux
