### ISSUE TITLE
Issue when trying to connect to turned off Bitalino Device

### ISSUE THREAD

**Issue by a-fazal** [BITalinoWorld/revolution-android-api#9]
When you try to connect to a turned off Bitalino device, the API tries to connect repeatedly to the device. When you disconnect, it throws a Bitalino device not connected error, and the API keeps trying to connect. The main issue is when you then turn the Bitalino and try to connect, that first thread from when you tried to connect to it turned off is still in a connection lost loop, which prevents the connection to the Bitalino. This could happen if someone lets say forgot to turn on the Bitalino.

**Comment by GRamosPlux** [comment]
Dear **@hypergalaxy**,

Thank you very much for your important alert regarding this undesirable behaviour!

Due to your detailed description, we were able to replicate and fix the behaviour.
In the recently committed version, the default action taken when device is disconnected was changed and auto-reconnect is not currently taking place.

I truly hope that these changes could be helpful, however, if you don't consider them effective, please, do not hesitate to alert me and I will reopen the issue.
